version: '3'

services:
  app:
    build: ./app
    container_name: website
    restart: unless-stopped
    env_file:
      - proxy.env
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
