version: '3'

services:
  app:
    build: ./app
    container_name: website
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=albanbruder.de,www.albanbruder.de
      - LETSENCRYPT_HOST=albanbruder.de,www.albanbruder.de
      - LETSENCRYPT_EMAIL=admin@albanbruder.de
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
